# Generated by Django 5.0 on 2024-02-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=500)),
                ('joylashuvi', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Fuqoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=200)),
                ('Familyasi', models.CharField(max_length=200)),
                ('Sharfi', models.CharField(max_length=200)),
                ('Rasmi', models.ImageField(upload_to='Fuqaro')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Jinoyatchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=200)),
                ('Familyasi', models.CharField(max_length=200)),
                ('Sharfi', models.CharField(max_length=200)),
                ('Rasmi', models.ImageField(upload_to='jinoyatchi')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Qarindosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=200)),
                ('Familyasi', models.CharField(max_length=200)),
                ('Sharfi', models.CharField(max_length=200)),
                ('Rasmi', models.ImageField(upload_to='qarindosh')),
                ('bogliq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.fuqoro')),
            ],
        ),
        migrations.CreateModel(
            name='Safarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaqti', models.DateTimeField()),
                ('Fuqoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.fuqoro')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.hudud')),
            ],
        ),
    ]
